title: Yiyang Wang Homepage
page-top-title: Yiyang Wang Homepage
top-section-bg-text: A Year-1 Phd Student of HKU
home-subtitle: Yiyang Wang
copyright-text: '&copy; Yiyang Wang 2025. All Rights Reserved. Template by Jerry Yin From <a href="https://github.com/JerryYin777/JerryYin777.github.io">This Repo</a>.'
